version: '3'
services:
  web:
    image: php:7.2-apache
    container_name: apache
    ports :
     - "80:80"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
